version: "3"
services:
  go_admin:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=go_admin
    ports:
      - "3306:3306"
    volumes:
      - go_admin:/var/lib/mysql
    networks:
      - go_admin

  phpmyadmin-compose:
    image: phpmyadmin
    environment:
      - PMA_HOST=go_admin
    ports:
      - "8090:80"
    depends_on:
      - go_admin
    networks:
      - go_admin

volumes:
  go_admin: {}

networks:
  go_admin:
